CMIP6_source_id.json
src/writeJson.py

Updated source_id to include `institution` in addition to model key and name

Fix #8 - Update source_id to include institution

---

CMIP6_grid.json
src/writeJson.py

Fix #6 - Add grid

---

CMIP6_formula_terms.json
src/writeJson.py

Fix #5 - Add formula_terms

---

src/json_to_html.py

Before submitting your pull request be sure that:
1. You haven't deleted any existing information
2. You haven't eliminated unnecessary blank lines or spaces during your work.
That makes our reviewing work harder and it could introduce unnecessary
conflicts with other pull requests.
----
*Note*: You can safely remove this text before submitting your work.

Json to html

---

CMIP6_experiment_id.json
src/writeJson.py

Fix #19 - Update VolMIP info (Davide Zanchettin)

Update VolMIP info (Davide Zanchettin)

---

CMIP6_frequency.json
src/writeJson.py

As per #24 @martinjuckes added `1hrClimMon`

Issue24 durack1 add frequency1hr clim mon

---

CMIP6_experiment_id.json
src/writeJson.py

Fix #27 - further experiment tweaks from @dlawrenncar

Update LUMIP experiment details

---

CMIP6_experiment_id.json
src/writeJson.py

Fix #27 - 
@dlawrenncar this should solve it

land-noShiftcultivate to land-noShiftCultivate

---

src/jquery.dataTables.js
src/json_to_html.py

@taylor13 this should get us along way down the path of the html formatting tweaks.
fix #25

Issue25 durack1 json to html tweaks

---

CMIP6_source_id.json
src/writeJson.py

Fix #34 - Update source_id format and contents

Issue35 durack1 Update source_id format and contents

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

#28 - Working to correct invalid merge
@dnadeau4 [WIP] is notation (in my head) for "work in progress" so please do not merge

issue28 durack1 include version status in json output

---

src/json_to_html.py

Fix #25 - Remove _ characters from table headings - @taylor13

issue25 durack1 remove '_' characters from html table headings

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

#28 - updated version info from repo to per file versioning

Updated versioning to per file basis

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Fix #28 - Revise versioning information

issue28 durack revise version info in json output

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Fix #53 - Update source_id template to maintain consistency with ES-DOC

issue53 durack update source_id template

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Fix #57 - Correct activity_id typo MIP -> CMIP

Issue57 durack1 Correct activity_id typo MIP -> CMIP

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Fix #49 - Add new grid_label entries

Issue57 durack1 Add new grid_label entries

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Fix #63 - Add institution_id NUIST

Issue63 durack1 Add institution_id NUIST

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Fix #67 - Add institution_id NIMS-KMA

Issue67 durack1 add institution id nims kma

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Fix #69 - Update tier info for AerChemMIP experiments

Issue63 durack1 Revise tiers for AerChemMIP experiments

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Fix #68 - Add AerChemMIP experiments, piClim-SO2, piClim-OC, piClim-NH3

Issue63 durack1 Add AerChemMIP experiments

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Rerun to confirm updates

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Update code to convert to per file commits

Convert to per file commits

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Fix #102 
@dnadeau4 this should work for you now

Issue102 durack1 add pcmdi test to source

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue98 durack1 update institution id bnu

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue90 durack1 add institution_id EC-Earth-Consortium

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue89 durack1 update institution_id MIROC

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue97 durack1 update experiment_id deforest-globe

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue79 durack1 revise RFMIP experiment_ids

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue81 durack1 RFMIP experiment_id caps tweaks

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue82 durack1 rfmip experiment id renames sp aer

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue77 durack1 revise activity_id for ssp370

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue75 durack1 revise experiment_id volc-cluster-mill

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue74 durack1 correct experiment_id instances of LND -> LAND

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue103 durack1 register experiment_id ism-ctrl-std

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue104 durack1 register experiment_id ism-asmb-std

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue105 durack1 register experiment_id ism-bsmb-std

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Fix instance of ['AER', 'CHEM,', 'BGCM']

Fix source type syntax

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue129 durack1 add institution_id CNRM

---

CMIP6_activity_id.json
CMIP6_coordinate.json
CMIP6_experiment_id.json
CMIP6_formula_terms.json
CMIP6_frequency.json
CMIP6_grid.json
CMIP6_grid_label.json
CMIP6_grid_resolution.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue131 durack1 revise source_type entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue138 durack1 register institution_id MESSy-Consortium

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue78 durack1 revise AerChemMIP experiment info

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue73 durack1 revise experiment_id 1pctCO2Ndep

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue99 durack1 register source_id BNU-ESM-1-1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue91 durack1 register source_id EC-EARTH-3

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue92 durack1 register source_id EC-EARTH-3-HR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue93 durack1 register source_id EC-Earth-3-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue115 durack1 register institution_id CNRM-CERFACS

---

CMIP6_required_global_attributes.json

change grid_resolution to nominal_resolution

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue84 durack1 register source_id NorEMS2-LME

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue85 durack1 register source_id NorESM2-MH

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue86 durack1 register source_id NorESM2-LMEC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue87 durack1 register source_id NorESM2-HH

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue88 durack1 register source_id NorESM2-MM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue156 durack1 register source_id NorESM2-LM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Fix #156 
Systematic fix of #157

Issue156 durack1 revise source_id NorESM various

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue169 durack1 experiment_id update ssp370 activity_id

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue170 durack1 add experiment_id 1pctCO2-4xext

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/json_to_html.py
src/writeJson.py

Issue172 durack1 institution id create html

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue178 durack1 frequency_id add 1hr

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue177 durack1 source_id add GISS-E2 variants

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/writeJson.py

Issue183 durack1 register institution_id NERC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue93 durack1 update source_id EC-Earth3-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue94 durack1 register source_id EC-Earth-3-CC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue184 durack1 register multiple source_ids HadGEM3 and UKESM1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue115 durack1 register multiple CNRM source_ids

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue115 durack1 revise source_id for multiple CNRM configurations

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue191 durack1 register multiple EC-Earth-3 source_ids

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue195 durack1 register multiple MPI source_ids

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue201 durack1 update activity_id highres-future start_year

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue202 durack1 add experiment_id spinup-1950

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/writeJson.py

Issue205 durack1 update institution_id FIO-SOA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/writeJson.py

Issue207 durack1 register institution_id AWI

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue210 durack1 register source_id AWI-CM-1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/writeJson.py

Issue209 register institution_id FIO-RONM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue208 durack1 register source_id MRI-ESM2-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue168 durack1 revise experiment id values for ismip

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue208 durack1 revise source_id MRI-ESM2-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue217 durack1 register source_id EMAC-2-53-AerChem

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue217 durack1 revise source id emac 2 53 aer chem

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Fix #221 
@taylor13 @jypeter here are the updates into the master - please check for the correct format and if there's an issue, reopen this issue

Issue221 durack1 update license info

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue210 durack1 revise source_id AWI-CM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_source_id.html
src/writeJson.py

Fix #191 
@MartinaSt pinging you here!

Issue191 durack1 revise several EC-Earth3 configurations

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/writeJson.py

Issue225 durack1 add institution_id THU

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/json_to_html.py
src/writeJson.py

Fix #1 
Fix #61 
Fix #136
Fix #137 
Fix #242 
Fix #243 
@taylor13 please review

Issue1 durack1 update experiment_id from spreadsheet (MIP-chair review)

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/json_to_html.py
src/writeJson.py

Reverts WCRP-CMIP/CMIP6_CVs#252

Revert "Issue249 durack1 source_id augment info request"

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/json_to_html.py
src/writeJson.py

Issue249 durack1 source_id augment info request

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue281 frequency add yrClim

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue276 durack1 add missing activity_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/writeJson.py

Issue284 durack1 revise institution_id CMCC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/json_to_html.py
src/writeJson.py

Fix #264 
@taylor13 @dnadeau4 pinging you both here as these changes will require propagation across to the PCMDI/cmip6-cmor-tables#52

Issue264 durack1 reconfigure source_id format

---

src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/json_to_html.py

Update html headers; #299

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Fix #293 
Correct #292 ocean entry

Issue293 durack1 register source_id CMCC-CM2-HR5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue295 durack1 register source_id CMCC-CM2-VHR4

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue296 durack1 register source_id CMCC-ESM2-SR5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue297 durack1 register source_id CMCC-ESM2-HR5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue330 durack1 register source_id CanESM5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue341 durack1 rename experiment id highresSST-4co2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue342 durack1 frequency augment format with identifiers

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_source_id.html
src/writeJson.py

Issue358 durack1 register source_id INM-CM5-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue197 durack1 revise multiple MPI source_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_source_id.html
src/writeJson.py

Issue115 durack1 revise source_id CNRM-CM6-1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json

Issue191 durack1 revise EC-EARTH3-HR ocean description

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue229 durack1 update multiple MIROC source_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/writeJson.py

Issue386 durack1 register institution_id SNU

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue392 durack1 register source_id IPSL-CM6A-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Ref #413 
There are still some clarifications remaining with #413, so will no auto-close with this PR

Issue413 durack1 add frequency mon pt

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html

Fix #318 
@aradhakrishnanGFDL these changes should reflect the final versions. We're following the standard format of the CVs.

Issue318 durack1 revise multiple gfdl source ids

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/writeJson.py

Issue421 durack1 register institution_id NIWA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/writeJson.py

Issue426 durack1 register institution_id CAS

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Issue431 durack1 fix outstanding source_id issues

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Issue431 durack1 additional fix NICAM16-9S

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/writeJson.py

Fix #423 
Fix type inconsistencies for `additional_allowed_model_components` variables for various experiments

Issue423 durack1 correct experiment_id components LUMIP LS3MIP

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/writeJson.py

Issue446 durack1 register institution_id DWD

---

src/cleanupTags.py

cleanupTags.py created and run

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_institution_id.html
src/writeJson.py

Issue459 durack1 register institution_id AER

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_source_id.html
src/writeJson.py

Issue454 durack1 remove source_id ACCESS-1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/writeJson.py

Issue457 durack1 revise source_id entries HadGEM3 and UKESM1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6Lib.py
src/CMIP6_experiment_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue378 durack1 validate source id entries against CV lists

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6Lib.py
src/writeJson.py

Cleanup after CV validation for source_id and experiment_id

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6Lib.py
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id KIOST

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6Lib.py

Update versioning process

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue469 durack1 register source_id KIOST-ESM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Update activity_participation for source_id CNRM-CM6-1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Update activity_participation entries to include CMIP

---

README.md

Update README.md with badge

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/writeJson.py

Issue468 durack1 update version processing

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CAS-ESM1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id VRESM-1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/versionHistory.json
src/writeJson.py

Updated to include ARTS-2-3; Awaiting cohort guidance

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id LBLRTM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id GFDL-ESM4 to include CDRMIP

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6Lib.py
src/writeJson.py

Add CMIP6 doc reference in version history

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id NESM3

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Register insitution_id IIASA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/versionHistory.json
src/writeJson.py

Revise OMIP JRA55-do entry

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise MPI-ESM1-2-HR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise ICON-ESM-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise MPI-ESM-1-2-HAM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise CAS FGOALS* activity_participation

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise NASA-GISS source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id GISS-E3-G

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id UofT, source_id UofT-CCSM4

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise MOHC source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue195 durack1 revise source_id MPI-ESM1-2-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id BNU-ESM-1-1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id deforest-globe

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise MIROC source_ids

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CESM2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise CESM2 activity_participation

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Revise institution_id NCC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id UKESM1-0-LL

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id KACE-1-0-G

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id E3SM-Project

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id UTAS

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Revise institution_id CSIRO-ARCCSS-BoM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id CSIRO

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id GFDL-CM4C192

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id ACCESS-ESM1-5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id ACCESS-CM2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id E3SM-1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise AWI source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CSIRO-Mk3L-1-3

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id INM-CM4-8

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id E3SM1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id GFDL-OM4p5B

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id CSIRO-Mk3L-1-3

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id DKRZ

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Issue566 durack1 register institution_id UA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id MCM-UA-1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Deregister institution_id IIASA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_institution_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id ECMWF

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id ECMWF-IFS-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id ECMWF-IFS-HR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id ECMWF-IFS-MR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id MPI-ESM1-2-HR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/versionHistory.json
src/writeJson.py

Revise LS3MIP experiment_ids, add land-ssp126

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue590 durack1 revise source_id MIROC6

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/json_to_html.py
src/versionHistory.json
src/writeJson.py

Issue318 durack1 revise gfdl source id release year

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/json_to_html.py
src/versionHistory.json
src/writeJson.py

Issue592 durack1 experiment_id update piClim* allowed components

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue594 durack1 update experiment_id CDRMIP experiments

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue407 durack1 revise multiple bcc source id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue318 durack1 revise multiple GFDL source_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise multiple NICAM source_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id AWI-ESM-1-1-LR, amend AWI-CM-1-1-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id esm-ssp534-over

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise specs_doc ref; CNRM-CM6-1 and CNRM-ESM2-1 activity_participation fields

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Correct CNRM-ESM2-1 activity_participation

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise CNRM-ESM2-1 activity_participation

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id AS-RCEC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id TaiESM1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id values, BGC as allowed component

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise institution_id AS-RCEC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Fix #559 
@treerink @shutingdk these changes are what I can ascertain were in your change file. In future please provide a direct diff so that these changes can be more easily ascertained

Revise source_id values for EC-Earth3 configurations

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise LS3MIP experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise DCPP experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id LBLRTM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CESM2-WACCM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CESM2-SE

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id RRTMG-SW

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id pa-futAntSIC-ext

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id RTE-RRTMGP-Consortium

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id RTE-RRTMGP-181204

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id RTE-RRTMGP-181204

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id MPI-ESM1-2-XR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id CanESM5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CanESM5-CanOE

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise MPI-M source_ids

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise CCCma institution_id

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise multiple UKESM1-0 source_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise GeoMIP experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise CNRM-CM6-1 source_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise OMIP*-spunup experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register GFDL RFMIP model contributors

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Update VRESM/CSIR-CSIRO registration

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise multiple MIROC registrations

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Update RFMIP experiment descriptions

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register 8 new C4MIP experiments

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id NASA-GSFC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/json_to_html.py

Update html page length defaults

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id EMAC-2-53-AerChem

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id NorESM1-1-ME

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise HadGEM3-GC31 source_ids

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue696 durack1 revise source id nor esm1 lm

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id NorESM1-LM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id MRI-AGCM3-2-H and revise MRI-AGCM3-2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id ssp534-over-bgc

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise numerous GeoMIP experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id BESM-2-7 to BESM-2-9

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise multiple AerChemMIP experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise multiple CFMIP experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise multiple DCPP experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise sub_experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/versionHistory.json
src/writeJson.py

Revise AerChemMIP experiment_id histSST-1950HC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id CNRM-CM6-1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Correct omip2 non-unicode char issue; implement checks

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id CAMS-CSM1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id omip2-spunup

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/writeJson.py

Revise README.md

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise multiple MPI source_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id ssp370SST-ssp126Lu

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Add experiment_id histSST-noLu (AerChemMIP)

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Fix #740 
@charliepascoe @taylor13

Revise experiment_id esm-hist-ext

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id AWI-ESM-2-1-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id AWI-ESM-2-1-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id EC-Earth3

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id KIOST-ESM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CESM2-FV2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CESM2-WACCM-FV2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise source_id GFDL-CM4

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id ssp370SST

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register institution_id RUBISCO

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id IPSL-CM7A-ATM-HR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id IPSL-CM7A-ATM-LR

---

src/cleanupTags.py

Cleanup missing release `6.2.37.2`

Use cleanupTags.py to fix 6.2.37.2 missing tag

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise institution_id FIO-QLNM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Rename source_id NorESM1-LM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id E3SM-1-1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id E3SM-1-1-ECA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Revise experiment_id entries hist-spAer-aer and hist-spAer-all

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Fix #775 
Ref PCMDI/cmip6-cmor-tables#260

Revise source_id E3SM-1-1 for 1024 char lim

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Fix #776 
Ref PCMDI/cmip6-cmor-tables#260

Revise source_id E3SM-1-1-ECA for 1024 char lim

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Register source_id CESM1-1-CAM5-CMIP5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
mip_era.json
src/CMIP6_experiment_id.html
src/CMIP6_institution_id.html
src/CMIP6_source_id.html
src/versionHistory.json
src/writeJson.py

Issue786 durack1 register source_id NorESM1-F

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id NorESM1-F

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id E3SM-1-1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id E3SM-1-1-ECA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id GISS-E2-1-G

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise and rename source_id GISS-E2-1-MA-G

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id FGOALS-g3

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register 3 new FAFMIP experiment_ids

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id GFDL-ESM4

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise institution_id CSIRO-ARCCSS-BoM; Update ACCESS* regos

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id ACCESS-CM2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id ACCESS-ESM1-5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id FGOALS-f3-L

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id AWI-CM-1-1-MR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id HadGEM3-GC31-LL

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register institution_id UCI

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id CESM1-WACCM-SC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id 4AOP-v1-5

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue832 durack1 revise source_id INM-CM4-8

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id INM-CM5-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register DAMIP experiment_id hist-totalO3

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Cleanup experiment_id grammar inconsistencies

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id EC-Earth3-Veg

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise multiple CMCC source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Deregister multiple CMCC source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Fix #849 
Fix PCMDI/cmip6-cmor-tables#278
Ref PCMDI/cmor#541

Issue849 durack1 add external variables to required global attributes

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Fix #849 
Ref PCMDI/cmip6-cmor-tables#278
Ref PCMDI/cmor#541

Reverting addition of external_variables to required_global_attributes

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id CAS-ESM1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id FGOALS-f3-H

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id GISS-E2-1-H

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue858 durack1 revise source_ids GISS-E2-1-H, GISSE3-G

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/cleanupTags.py
src/versionHistory.json
src/writeJson.py

Register source_ids HiRAM-SIT-HR, HiRAM-SIT-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/cleanupTags.py
src/versionHistory.json
src/writeJson.py

Issue861 durack1 revise multiple IPSL-CM source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/cleanupTags.py
src/versionHistory.json
src/writeJson.py

Issue868 durack1 revise experiment_id histSST-noLu

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/cleanupTags.py
src/versionHistory.json
src/writeJson.py

Issue869 durack1 register source_id UKESM1-ice-LL

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/cleanupTags.py
src/versionHistory.json
src/writeJson.py

Issue867 durack1 revise multiple ssp370SST-low* experiment_id values

---

src/CMIP6Lib.py

Add durolib functions

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise multiple MIROC source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue880 durack1 revise source_id MIROC-ES2H-NB

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id IPSL-CM6A-LR-INCA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id IPSL-CM5A2-INCA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise experiment_id histSST-noLu

---

README.md

Revise README.md to reflect backward compatibility (#885)

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id NorESM2-LM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise *-cmip5 experiment_id values

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue896 durack1 revise source_id MIROC-ES2H

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id IPSL-CM6A-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id MCM-UA-1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise multiple CNRM- source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register institution_id PNNL-WACCEM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id CAM-MPAS

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/json_to_html.py
src/versionHistory.json
src/writeJson.py

Revise source_id CAM-MPAS

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id INM-CM5-H

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id CESM2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id CESM2-WACCM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register additional PMIP experiment_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise PMIP experiment_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
mip_era.json
src/writeJson.py

Validate source/institution_id entry lengths

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id CESM1-CAM5-SE-HR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id CESM1-CAM5-SE-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise experiment_id ssp370-lowNTCFCH4

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register institution_id NTU

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id MPI-ESM-1-2-HAM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_ids UKESM1-0-LL, HadGEM3-GC31-LL

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id IPSL-CM6A-LR-INCA

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Fix #959 
ping @taylor13 @MartinaSt @matthew-mizielinski

Revise source_id HadGEM3-GC31-MM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id ACCESS-OM2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id ACCESS-OM2-025

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_ids EC-Earth3 and IITM-ESM

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id CAM-MPAS-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

issue973 add CovidMIP experiment_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id MPI-ESM1-2-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id E3SM-1-0

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id CESM1-WACCM-SC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id TaiESM1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise multiple E3SM source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise experiment_id historical parent experiments

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id MIROC-ES2L

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise multiple EC-Earth source_id entries

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id MIROC-ES2H

---

.github/Institution_registration_template.md
.github/Model_registration_template.md

Ref #997 
@matthew-mizielinski @taylor13 @MartinaST

Update issue templates re: AR6 deadlines (#997)

---

.github/ISSUE_TEMPLATE.md
.github/Institution_registration_template.md
.github/Model_registration_template.md

Ref #1006 #997 
@matthew-mizielinski @taylor13 @MartinaSt

Issue997 durack1 notification about continued cv updates

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_ids IPSL-CM5A2-INCA, IPSL-CM6A-LR

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_ids GFDL-ESM4, GFDL-CM4

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id CMCC-ESM2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id GISS-E2-2-H

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id IPSL-CM6A-MR1

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id IPSL-CM6A-MR025

---

src/versionHistory.json

Resolve src/versionHistory.json conflict

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id E3SM-1-0 add PAMIP

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id ICON-ESM-LR

---

src/googleAnalyticsTag.js
src/json_to_html.py

add GA tag to html

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id TaiESM1-TIMCOM2

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Covers #1043, #1044, #1045, #1046 : The addition of LR, MR, HR and VHR resolution variants of IPSL-CM6A-ATM-ICO

Register source_id IPSL-CM6A-ATM-ICO series

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Update IPSL source_ids; remove IPSL-CM7*, add IPSL-CM6A-ATM-LR-REPROBUS

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise source_id EC-Earth3-CC

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised MCM-UA-1-0 license history

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised numerous EC-Earth3 license histories

---

CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue1078 durack1 revise numerous IPSL source_id license entries

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/CMIP6Lib.py
src/versionHistory.json
src/writeJson.py

Issue1042 durack1 add CMIP6 DRS templates

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revise 5 NorESM2 source_id license histories; deregister *LME*, and *MH

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue1083 durack1 revise multiple GFDL licenses

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Correct erroneous NorESM2-MH deregistration

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised licence histories for AS-RCEC and NTU models (TaiESM*, HiRAM*)

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised license histories for CSIRO, CSIRO-ARCCSS and CSIRO-COSIMA models

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised license histories for MIROC* models; Deregister NICAM16-9D-L78

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue1094 durack1 revised multiple MIROC NICAM* license entries

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue1095 durack1 revise multiple E3SM license entries

---

.github/ISSUE_TEMPLATE.md
CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue1100 durack1 deregister BNU-ESM-1-1 and institution_id BNU

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Deregister source_id CNRM-ESM2-1-HR

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised 4 MPI-M* source_id license histories

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised 3 MIROC NICAM* source_id license histories

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised 4 MIROC* source_id license histories

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Deregistered two EMAC-2* source_id entries

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Deregistered source_id UofT-CCSM4 and institution_id UofT

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Deregistered source_id BESM-2-9 and institution_id INPE

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Deregistered source_id CSIRO-Mk3L-1-3 and institution_id UTAS

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Registered source_id E3SM-2-0

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised source_id E3SM-2-0

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised CMOR3 derived source 1024 char limit test

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Deregister source_id GFDL-GLOBAL-LBL

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised CMOR3 derived source 1023 char limit test

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue1130 durack1 revise multiple ECMWF source_id entries

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised CIESM source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised MPI-ESM-1-2-HAM source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised 3 MRI-* source_id license histories

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register institution_id UCSB for E3SM-1-0

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Ref #1076 
This awaiting `EC-Earth3-GrIS` publication to close out #1076

Revised EC-Earth3-HR source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised 4 IPSL* source_id license histories

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised IITM-ESM source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised 2 CCCma source_id license histories

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised FIO-ESM-2-0 source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised 3 BCC* source_id license histories

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised KACE-1-0-G source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised KIOST-ESM source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised CAMS-CSM1-0 source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Register source_id CanESM5-1

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Issue1168 durack1 revise multiple CAS source_id licenses

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Fix #1170 
Ref #1113 
@CMIP-IPO @peace2016

Revised NESM3 source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Fix #1172 
Ref #1113 
@CMIP-IPO @pernak18

Revised 4 AER* source_id license histories

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Fix #1174 
Ref #1113 
@CMIP-IPO @sjh11556

Revised SAM0-UNICON source_id license history

---

CMIP6_DRS.json
CMIP6_activity_id.json
CMIP6_experiment_id.json
CMIP6_frequency.json
CMIP6_grid_label.json
CMIP6_institution_id.json
CMIP6_license.json
CMIP6_nominal_resolution.json
CMIP6_realm.json
CMIP6_required_global_attributes.json
CMIP6_source_id.json
CMIP6_source_type.json
CMIP6_sub_experiment_id.json
CMIP6_table_id.json
README.md
docs/CMIP6_experiment_id.html
docs/CMIP6_institution_id.html
docs/CMIP6_source_id.html
docs/CMIP6_source_id_licenses.html
mip_era.json
src/versionHistory.json
src/writeJson.py

Revised E3SM-2-0 source_id license history

---

README.md

Add contribs to README.md (#1181)

---

README.md

add acknow/funding attribution

---

README.md

add PCMDI Logo to acknows

---

LICENSE-CC-BY

Add CC BY 4.0 license

---

docs/googled7d7e1a0438a41d7.html

enable google search console (#1205)

---

CITATION.cff
README.md
src/writeJson.py

adding CITATION.cff; Zenodo DOI (#1231)
